### ISSUE TITLE
External 파일은 바로가기가 생성 안되는게 맞음?

### ISSUE THREAD

**Issue by arbiter11able** [Insiro/GenshinVoiceManager#5]
원본 오디오에셋 폴더 안에 코리안 폴더 바로가기 생기자늠

들어가보면 External 붙은 파일은 죄다 바로가기 처리가 안되는데 이건 왜 그런거임?

매번 수동으로 하다가 이상해서 물어봄
![image](https://github.com/Insiro/GenshinVoiceManager/assets/148313427/9cb3f7c0-c990-4f16-a502-bff07db8ab96)
지금 심링크 복구 후 모드 적용해보면 이런 상태임

그리고 생성한 모드도 적용이 안되서 수동으로 했었는데 혹시 이런 증상 해결방법 있나 싶어서 물어봄

**Comment by Insiro** [comment]
모드폴더 자체가 링크걸려서 저장이 됨
external은 그 자리에 생성이 된것
만약 external중 생성이 안된거는 역시 링크가 걸림

**Comment by arbiter11able** [comment]
모드 생성을 다시 해서 모드 적용하니까 됐음

근데 지금 라이오슬리 전투 음성이 아예 안나오는 증상이 있는데 이거 어케 해결하지?

**Comment by Insiro** [comment]
음성이 구버전음성인듯
그경우 음성을 다시다운로드 후 생성해야함
이런이유떄문에 업데이트때마다 복구후 업뎃, 재생성해야하는것..
